import { execSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  addPlaywrightAgentConfigs,
  addPlaywrightToCodexConfig,
  addPlaywrightToOpenCodeConfig,
  detectTrackedStateFiles,
  ensureRootGitignore,
  initProject,
  mergeClaudePlaywrightSettings,
  mergeClaudeLocalSettings,
  mergeCodexProjectTrust,
  mergeOpenCodePermission,
  mergeOpenCodePlaywrightPermission,
  previewLegacyMigration,
} from './init.js';
import { TENET_MCP_TOOL_NAMES } from '../mcp/tools/tool-names.js';

const tempDirs: string[] = [];

const createTempDir = (): string => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tenet-test-'));
  tempDirs.push(dir);
  return dir;
};

const stripGeneratedSkillMetadata = (content: string): string =>
  content.replace(/\n<!-- Generated by Tenet .*? -->\n+/, '\n');

afterEach(() => {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
});

describe('initProject', () => {
  it('initializes fresh project with expected directories and template files', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const tenetRoot = path.join(projectPath, '.tenet');
    const expectedDirs = [
      'project',
      'project/design-components',
      'runs',
      'archive',
      'knowledge',
      'status',
      'state-snapshot',
      '.state',
    ];

    for (const dir of expectedDirs) {
      expect(fs.existsSync(path.join(tenetRoot, dir))).toBe(true);
    }

    // Fresh init must NOT scaffold legacy directories — they only appear via migration.
    for (const legacyDir of ['interview', 'spec', 'harness', 'journal', 'steer', 'bootstrap', 'visuals']) {
      expect(fs.existsSync(path.join(tenetRoot, legacyDir))).toBe(false);
    }

    const expectedFiles = [
      'project/overview.md',
      'project/architecture.md',
      'project/product.md',
      'project/testing.md',
      'project/design.md',
      'status/status.md',
      'status/job-queue.md',
      'status/backlog.md',
      'state-snapshot/README.md',
      '.gitignore',
    ];

    for (const file of expectedFiles) {
      expect(fs.existsSync(path.join(tenetRoot, file))).toBe(true);
    }

    const statusContent = fs.readFileSync(path.join(tenetRoot, 'status/status.md'), 'utf8');
    expect(statusContent).toContain('# Status');
    expect(statusContent).toContain('- mode: unset');

    const gitignore = fs.readFileSync(path.join(tenetRoot, '.gitignore'), 'utf8');
    expect(gitignore).toContain('.state/');
    expect(gitignore).toContain('!state-snapshot/');
  });

  it('copies SKILL.md into .claude/skills/tenet', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const copiedSkillPath = path.join(projectPath, '.claude', 'skills', 'tenet', 'SKILL.md');
    expect(fs.existsSync(copiedSkillPath)).toBe(true);

    const initFile = fileURLToPath(import.meta.url);
    const sourceSkillPath = path.resolve(path.dirname(initFile), '../../skills/tenet/SKILL.md');
    const copiedContent = fs.readFileSync(copiedSkillPath, 'utf8');
    const sourceContent = fs.readFileSync(sourceSkillPath, 'utf8');
    expect(copiedContent).toContain('Generated by Tenet');
    expect(copiedContent).toContain('from skills/tenet/SKILL.md');
    expect(stripGeneratedSkillMetadata(copiedContent)).toBe(sourceContent);
  });

  it('copies phase docs into .claude/skills/tenet/phases', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const phasesDir = path.join(projectPath, '.claude', 'skills', 'tenet', 'phases');
    expect(fs.existsSync(phasesDir)).toBe(true);

    const expectedPhases = [
      '00-context-bootstrap.md',
      '01-interview.md',
      '02-spec-and-harness.md',
      '03-visuals.md',
      '04-decomposition.md',
      '05-execution-loop.md',
      '06-evaluation.md',
    ];

    for (const phase of expectedPhases) {
      expect(fs.existsSync(path.join(phasesDir, phase))).toBe(true);
    }
    expect(fs.existsSync(path.join(phasesDir, '00-brownfield-scan.md'))).toBe(false);
  });

  it('throws when .tenet already exists', () => {
    const projectPath = createTempDir();
    fs.mkdirSync(path.join(projectPath, '.tenet'), { recursive: true });

    expect(() => initProject(projectPath)).toThrowError(/\.tenet already exists.*--upgrade/);
  });

  it('creates lifecycle project templates and no legacy harness file', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const projectDoc = fs.readFileSync(path.join(projectPath, '.tenet', 'project', 'overview.md'), 'utf8');
    expect(projectDoc).toContain('Bootstrap placeholder');

    // Fresh init creates only the lifecycle layout — no legacy harness/current.md.
    expect(fs.existsSync(path.join(projectPath, '.tenet', 'harness'))).toBe(false);
  });

  it('writes .mcp.json for Claude Code auto-discovery', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const mcpJsonPath = path.join(projectPath, '.mcp.json');
    expect(fs.existsSync(mcpJsonPath)).toBe(true);

    const content = JSON.parse(fs.readFileSync(mcpJsonPath, 'utf8'));
    expect(content.mcpServers.tenet).toBeDefined();
    expect(content.mcpServers.tenet.command).toBe('tenet');
    expect(content.mcpServers.tenet.args).toEqual(['serve']);
  });

  it('merges into existing .mcp.json without overwriting other servers', () => {
    const projectPath = createTempDir();
    const mcpJsonPath = path.join(projectPath, '.mcp.json');
    fs.writeFileSync(mcpJsonPath, JSON.stringify({
      mcpServers: { other: { command: 'other-cmd', args: [] } }
    }), 'utf8');

    initProject(projectPath);

    const content = JSON.parse(fs.readFileSync(mcpJsonPath, 'utf8'));
    expect(content.mcpServers.other).toBeDefined();
    expect(content.mcpServers.tenet).toBeDefined();
  });

  it('writes opencode.json for OpenCode auto-discovery', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const configPath = path.join(projectPath, 'opencode.json');
    expect(fs.existsSync(configPath)).toBe(true);

    const content = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    expect(content.mcp.tenet).toBeDefined();
    expect(content.mcp.tenet.type).toBe('local');
    expect(content.mcp.tenet.command).toEqual(['tenet', 'serve']);
  });

  it('copies skill files into .agents/skills/tenet for Codex compatibility', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const codexSkillPath = path.join(projectPath, '.agents', 'skills', 'tenet', 'SKILL.md');
    expect(fs.existsSync(codexSkillPath)).toBe(true);

    const codexPhasesDir = path.join(projectPath, '.agents', 'skills', 'tenet', 'phases');
    expect(fs.existsSync(codexPhasesDir)).toBe(true);

    // Verify content matches source except generated metadata
    const initFile = fileURLToPath(import.meta.url);
    const sourceSkillPath = path.resolve(path.dirname(initFile), '../../skills/tenet/SKILL.md');
    const copiedContent = fs.readFileSync(codexSkillPath, 'utf8');
    expect(copiedContent).toContain('Generated by Tenet');
    expect(copiedContent).toContain('from skills/tenet/SKILL.md');
    expect(stripGeneratedSkillMetadata(copiedContent)).toBe(fs.readFileSync(sourceSkillPath, 'utf8'));
  });

  it('writes .codex/config.toml for Codex MCP discovery', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    const configPath = path.join(projectPath, '.codex', 'config.toml');
    expect(fs.existsSync(configPath)).toBe(true);

    const content = fs.readFileSync(configPath, 'utf8');
    expect(content).toContain('[mcp_servers.tenet]');
    expect(content).toContain('command = "tenet"');
    expect(content).toContain('args = ["serve"]');
  });

  it('adds Playwright MCP to Codex config with tool approvals', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    addPlaywrightToCodexConfig(projectPath);

    const content = fs.readFileSync(path.join(projectPath, '.codex', 'config.toml'), 'utf8');
    expect(content).toContain('[mcp_servers.tenet]');
    expect(content).toContain('[mcp_servers.playwright]');
    expect(content).toContain('command = "npx"');
    expect(content).toContain('args = ["@playwright/mcp@latest"]');
    expect(content).toContain('[mcp_servers.playwright.tools.browser_navigate]');
    expect(content).toContain('approval_mode = "approve"');
  });

  it('adds Playwright MCP to OpenCode config without overwriting Tenet', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    addPlaywrightToOpenCodeConfig(projectPath);

    const content = JSON.parse(fs.readFileSync(path.join(projectPath, 'opencode.json'), 'utf8'));
    expect(content.mcp.tenet).toBeDefined();
    expect(content.mcp.playwright.type).toBe('local');
    expect(content.mcp.playwright.command).toEqual(['npx', '@playwright/mcp@latest']);
    expect(content.mcp.playwright.enabled).toBe(true);
  });

  it('adds Playwright MCP to all agent configs', () => {
    const projectPath = createTempDir();
    initProject(projectPath);

    addPlaywrightAgentConfigs(projectPath);

    const mcpJson = JSON.parse(fs.readFileSync(path.join(projectPath, '.mcp.json'), 'utf8'));
    const codexConfig = fs.readFileSync(path.join(projectPath, '.codex', 'config.toml'), 'utf8');
    const opencode = JSON.parse(fs.readFileSync(path.join(projectPath, 'opencode.json'), 'utf8'));
    const claudeSettings = JSON.parse(fs.readFileSync(path.join(projectPath, '.claude', 'settings.local.json'), 'utf8'));

    expect(mcpJson.mcpServers.playwright).toBeDefined();
    expect(codexConfig).toContain('[mcp_servers.playwright]');
    expect(opencode.mcp.playwright).toBeDefined();
    expect(opencode.permission.mcp.playwright).toBe('allow');
    expect(claudeSettings.enabledMcpjsonServers).toContain('playwright');
    expect(claudeSettings.permissions.allow).toContain('mcp__playwright__browser_navigate');
  });

  it('appends to existing .codex/config.toml without overwriting', () => {
    const projectPath = createTempDir();
    const codexDir = path.join(projectPath, '.codex');
    fs.mkdirSync(codexDir, { recursive: true });
    fs.writeFileSync(
      path.join(codexDir, 'config.toml'),
      '[mcp_servers.github]\ncommand = "gh-mcp"\n',
      'utf8',
    );

    initProject(projectPath);

    const content = fs.readFileSync(path.join(codexDir, 'config.toml'), 'utf8');
    expect(content).toContain('[mcp_servers.github]');
    expect(content).toContain('[mcp_servers.tenet]');
  });

  it('merges into existing opencode.json without overwriting other config', () => {
    const projectPath = createTempDir();
    const configPath = path.join(projectPath, 'opencode.json');
    fs.writeFileSync(configPath, JSON.stringify({
      model: 'claude-sonnet',
      mcp: { github: { type: 'local', command: ['gh-mcp'] } }
    }), 'utf8');

    initProject(projectPath);

    const content = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    expect(content.model).toBe('claude-sonnet');
    expect(content.mcp.github).toBeDefined();
    expect(content.mcp.tenet).toBeDefined();
  });

  it('adds portable state gitignore rules during upgrade without overwriting custom rules', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    fs.writeFileSync(path.join(tenetRoot, '.gitignore'), 'custom-rule\n', 'utf8');

    initProject(projectPath, { upgrade: true });

    const gitignore = fs.readFileSync(path.join(tenetRoot, '.gitignore'), 'utf8');
    expect(gitignore).toContain('custom-rule');
    expect(gitignore).toContain('.state/');
    expect(gitignore).toContain('!state-snapshot/');
    expect(fs.existsSync(path.join(tenetRoot, 'state-snapshot', 'README.md'))).toBe(true);
  });

  it('rewrites the legacy playwright_eval id in .tenet/critics.json on upgrade', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    fs.writeFileSync(
      path.join(tenetRoot, 'critics.json'),
      JSON.stringify(
        {
          version: 1,
          critics: [
            { id: 'code_critic', builtin: true, enabled: true },
            { id: 'playwright_eval', builtin: true, enabled: true },
            { id: 'my_custom', job_type: 'playwright_eval', prompt_file: '.tenet/critics/x.md' },
          ],
        },
        null,
        2,
      ),
      'utf8',
    );

    initProject(projectPath, { upgrade: true });

    const after = fs.readFileSync(path.join(tenetRoot, 'critics.json'), 'utf8');
    expect(after).not.toContain('playwright_eval');
    expect(after).toContain('"id": "interaction_e2e"');
    expect(after).toContain('"job_type": "interaction_e2e"');
    // Custom critic + enabled flags + structure preserved.
    expect(after).toContain('my_custom');
    expect(after).toContain('"enabled": true');
  });

  it('leaves a clean critics.json untouched on upgrade (idempotent)', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    const clean = JSON.stringify(
      {
        version: 1,
        critics: [
          { id: 'interaction_e2e', builtin: true, enabled: true, full_context: true },
        ],
      },
      null,
      2,
    );
    fs.writeFileSync(path.join(tenetRoot, 'critics.json'), clean, 'utf8');

    initProject(projectPath, { upgrade: true });

    expect(fs.readFileSync(path.join(tenetRoot, 'critics.json'), 'utf8')).toBe(clean);
  });

  it('adds full_context to pre-existing critic entries on upgrade, preserving formatting', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    // A pre-feature critics.json: compact one-line built-ins + a multi-line custom
    // critic, none carrying full_context.
    fs.writeFileSync(
      path.join(tenetRoot, 'critics.json'),
      '{\n  "version": 1,\n  "critics": [\n' +
        '    { "id": "code_critic", "builtin": true, "enabled": true },\n' +
        '    { "id": "test_critic", "builtin": true, "enabled": true },\n' +
        '    {\n' +
        '      "id": "security",\n' +
        '      "builtin": false,\n' +
        '      "enabled": false,\n' +
        '      "stage": "security_critic",\n' +
        '      "prompt_file": ".tenet/critics/security.md"\n' +
        '    }\n' +
        '  ]\n}\n',
      'utf8',
    );

    initProject(projectPath, { upgrade: true });

    const after = fs.readFileSync(path.join(tenetRoot, 'critics.json'), 'utf8');
    // One-line built-ins gained full_context inline and stayed one-line.
    expect(after).toContain(
      '{ "id": "code_critic", "builtin": true, "enabled": true, "full_context": true }',
    );
    expect(after).toContain(
      '{ "id": "test_critic", "builtin": true, "enabled": true, "full_context": true }',
    );
    // Multi-line custom critic: comma on the prior value, new key at the keys' indent.
    expect(after).toContain(
      '"prompt_file": ".tenet/critics/security.md",\n      "full_context": true\n    }',
    );

    // Idempotent: a second upgrade changes nothing.
    initProject(projectPath, { upgrade: true });
    expect(fs.readFileSync(path.join(tenetRoot, 'critics.json'), 'utf8')).toBe(after);
  });

  it('leaves an invalid critics.json untouched on upgrade', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    const broken = '{ "version": 1, "critics": [ { "id": "code_critic" ] }';
    fs.writeFileSync(path.join(tenetRoot, 'critics.json'), broken, 'utf8');

    initProject(projectPath, { upgrade: true });

    expect(fs.readFileSync(path.join(tenetRoot, 'critics.json'), 'utf8')).toBe(broken);
  });

  it('creates lifecycle docs during upgrade without overwriting existing project docs', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(path.join(tenetRoot, 'project'), { recursive: true });
    fs.writeFileSync(path.join(tenetRoot, 'project', 'overview.md'), '# Custom Overview\n', 'utf8');

    initProject(projectPath, { upgrade: true });

    expect(fs.readFileSync(path.join(tenetRoot, 'project', 'overview.md'), 'utf8')).toBe('# Custom Overview\n');
    expect(fs.existsSync(path.join(tenetRoot, 'project', 'architecture.md'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'project', 'product.md'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'project', 'testing.md'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'project', 'design.md'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'project', 'design-components'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'runs'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'archive'))).toBe(true);
  });

  it('moves legacy document dirs into archive/legacy-v1 on upgrade', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    const legacyDirs = ['spec', 'interview', 'decomposition', 'harness', 'journal', 'visuals', 'bootstrap', 'steer'];
    for (const dir of legacyDirs) {
      fs.mkdirSync(path.join(tenetRoot, dir), { recursive: true });
      fs.writeFileSync(path.join(tenetRoot, dir, 'note.md'), `# legacy ${dir}\n`, 'utf8');
    }
    fs.writeFileSync(path.join(tenetRoot, 'DESIGN.md'), '# legacy design\n', 'utf8');

    initProject(projectPath, { upgrade: true, migrateLegacy: true });

    for (const dir of legacyDirs) {
      expect(fs.existsSync(path.join(tenetRoot, dir))).toBe(false);
      expect(fs.readFileSync(path.join(tenetRoot, 'archive', 'legacy-v1', dir, 'note.md'), 'utf8')).toBe(`# legacy ${dir}\n`);
    }
    expect(fs.existsSync(path.join(tenetRoot, 'DESIGN.md'))).toBe(false);
    expect(fs.readFileSync(path.join(tenetRoot, 'archive', 'legacy-v1', 'DESIGN.md'), 'utf8')).toBe('# legacy design\n');
  });

  it('archives knowledge content but keeps an empty top-level knowledge/ for bootstrap', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(path.join(tenetRoot, 'knowledge'), { recursive: true });
    fs.writeFileSync(path.join(tenetRoot, 'knowledge', 'worker-queue.md'), '# Worker Queue\n', 'utf8');

    initProject(projectPath, { upgrade: true, migrateLegacy: true });

    // Legacy knowledge content is archived; the active-lane dir stays (empty) for bootstrap to refill.
    expect(fs.existsSync(path.join(tenetRoot, 'knowledge'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'knowledge', 'worker-queue.md'))).toBe(false);
    expect(fs.readFileSync(path.join(tenetRoot, 'archive', 'legacy-v1', 'knowledge', 'worker-queue.md'), 'utf8')).toBe('# Worker Queue\n');
  });

  it('prunes deleted skill phase files during upgrade', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    const phasesDir = path.join(projectPath, '.claude', 'skills', 'tenet', 'phases');
    fs.mkdirSync(phasesDir, { recursive: true });
    // A stale phase file that no longer exists in the bundled skill source.
    fs.writeFileSync(path.join(phasesDir, '00-brownfield-scan.md'), '# stale\n', 'utf8');

    initProject(projectPath, { upgrade: true });

    expect(fs.existsSync(path.join(phasesDir, '00-brownfield-scan.md'))).toBe(false);
    expect(fs.existsSync(path.join(phasesDir, '00-context-bootstrap.md'))).toBe(true);
  });

  it('leaves runtime lanes untouched during upgrade migration', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(path.join(tenetRoot, 'status'), { recursive: true });
    fs.mkdirSync(path.join(tenetRoot, 'state-snapshot'), { recursive: true });
    fs.writeFileSync(path.join(tenetRoot, 'status', 'status.md'), '# runtime status\n', 'utf8');
    fs.writeFileSync(path.join(tenetRoot, 'state-snapshot', 'keep.md'), '# keep\n', 'utf8');

    initProject(projectPath, { upgrade: true, migrateLegacy: true });

    expect(fs.readFileSync(path.join(tenetRoot, 'status', 'status.md'), 'utf8')).toBe('# runtime status\n');
    expect(fs.readFileSync(path.join(tenetRoot, 'state-snapshot', 'keep.md'), 'utf8')).toBe('# keep\n');
    expect(fs.existsSync(path.join(tenetRoot, 'archive', 'legacy-v1', 'status'))).toBe(false);
    expect(fs.existsSync(path.join(tenetRoot, 'archive', 'legacy-v1', 'state-snapshot'))).toBe(false);
  });

  it('does not migrate empty legacy dirs', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    fs.mkdirSync(path.join(tenetRoot, 'spec'), { recursive: true }); // empty

    initProject(projectPath, { upgrade: true, migrateLegacy: true });

    expect(fs.existsSync(path.join(tenetRoot, 'spec'))).toBe(true);
    expect(fs.existsSync(path.join(tenetRoot, 'archive', 'legacy-v1', 'spec'))).toBe(false);
  });

  it('is idempotent — a second upgrade does not re-migrate', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    fs.mkdirSync(path.join(tenetRoot, 'spec'), { recursive: true });
    fs.writeFileSync(path.join(tenetRoot, 'spec', 'oauth.md'), '# legacy oauth spec\n', 'utf8');

    initProject(projectPath, { upgrade: true, migrateLegacy: true });
    expect(fs.existsSync(path.join(tenetRoot, 'archive', 'legacy-v1', 'spec', 'oauth.md'))).toBe(true);

    // A legacy-looking dir recreated after migration must NOT be re-archived.
    fs.mkdirSync(path.join(tenetRoot, 'spec'), { recursive: true });
    fs.writeFileSync(path.join(tenetRoot, 'spec', 'payments.md'), '# stays at top level\n', 'utf8');

    initProject(projectPath, { upgrade: true, migrateLegacy: true });

    expect(fs.readFileSync(path.join(tenetRoot, 'spec', 'payments.md'), 'utf8')).toBe('# stays at top level\n');
    expect(fs.existsSync(path.join(tenetRoot, 'archive', 'legacy-v1', 'spec', 'payments.md'))).toBe(false);
  });

  it('does not migrate legacy dirs when migrateLegacy is not set', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });
    fs.mkdirSync(path.join(tenetRoot, 'spec'), { recursive: true });
    fs.writeFileSync(path.join(tenetRoot, 'spec', 'note.md'), '# legacy spec\n', 'utf8');

    initProject(projectPath, { upgrade: true });

    // No consent flag → the destructive move does not run.
    expect(fs.readFileSync(path.join(tenetRoot, 'spec', 'note.md'), 'utf8')).toBe('# legacy spec\n');
    expect(fs.existsSync(path.join(tenetRoot, 'archive', 'legacy-v1'))).toBe(false);
  });

  it('previewLegacyMigration reports alreadyMigrated and hasWork correctly', () => {
    const projectPath = createTempDir();
    const tenetRoot = path.join(projectPath, '.tenet');
    fs.mkdirSync(tenetRoot, { recursive: true });

    // Empty legacy dir is not listed as work.
    fs.mkdirSync(path.join(tenetRoot, 'spec'), { recursive: true });
    let preview = previewLegacyMigration(tenetRoot);
    expect(preview.alreadyMigrated).toBe(false);
    expect(preview.hasWork).toBe(false);
    expect(preview.dirs).not.toContain('spec');

    // Non-empty legacy dir + DESIGN.md show up as work.
    fs.writeFileSync(path.join(tenetRoot, 'spec', 'oauth.md'), '# legacy oauth\n', 'utf8');
    fs.writeFileSync(path.join(tenetRoot, 'DESIGN.md'), '# legacy design\n', 'utf8');
    preview = previewLegacyMigration(tenetRoot);
    expect(preview.hasWork).toBe(true);
    expect(preview.dirs).toContain('spec');
    expect(preview.files).toContain('DESIGN.md');

    // Once the archive marker exists, the migration reads as already done.
    fs.mkdirSync(path.join(tenetRoot, 'archive', 'legacy-v1'), { recursive: true });
    preview = previewLegacyMigration(tenetRoot);
    expect(preview.alreadyMigrated).toBe(true);
    expect(preview.hasWork).toBe(false);
  });
});

describe('state DB git safety', () => {
  const gitAvailable = (() => {
    try {
      execSync('git --version', { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  })();

  describe('ensureRootGitignore', () => {
    it('appends .tenet/.state/ to an existing root .gitignore without overwriting custom rules', () => {
      const projectPath = createTempDir();
      fs.writeFileSync(path.join(projectPath, '.gitignore'), 'node_modules\nbuild\n', 'utf8');

      ensureRootGitignore(projectPath);

      const content = fs.readFileSync(path.join(projectPath, '.gitignore'), 'utf8');
      expect(content).toContain('node_modules');
      expect(content).toContain('build');
      expect(content).toContain('.tenet/.state/');
    });

    it('does not create a root .gitignore when none exists', () => {
      const projectPath = createTempDir();
      ensureRootGitignore(projectPath);
      expect(fs.existsSync(path.join(projectPath, '.gitignore'))).toBe(false);
    });

    it('is idempotent — does not append the rule twice', () => {
      const projectPath = createTempDir();
      fs.writeFileSync(path.join(projectPath, '.gitignore'), 'node_modules\n', 'utf8');
      ensureRootGitignore(projectPath);
      ensureRootGitignore(projectPath);

      const content = fs.readFileSync(path.join(projectPath, '.gitignore'), 'utf8');
      expect((content.match(/\.tenet\/\.state\//g) ?? []).length).toBe(1);
    });
  });

  (gitAvailable ? describe : describe.skip)('detectTrackedStateFiles', () => {
    it('warns with the untrack command when the live DB is tracked by git', () => {
      const projectPath = createTempDir();
      execSync('git init', { cwd: projectPath, stdio: 'ignore' });
      fs.mkdirSync(path.join(projectPath, '.tenet', '.state'), { recursive: true });
      fs.writeFileSync(path.join(projectPath, '.tenet', '.state', 'tenet.db'), 'fake-db', 'utf8');
      execSync('git add -f .tenet/.state/tenet.db', { cwd: projectPath, stdio: 'ignore' });

      const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});
      detectTrackedStateFiles(projectPath);

      expect(warnSpy).toHaveBeenCalled();
      const message = warnSpy.mock.calls.map((call) => String(call[0])).join('\n');
      expect(message).toContain('tenet.db');
      expect(message).toContain('git rm --cached --ignore-unmatch');
      warnSpy.mockRestore();
    });

    it('also flags WAL sidecars when they are tracked', () => {
      const projectPath = createTempDir();
      execSync('git init', { cwd: projectPath, stdio: 'ignore' });
      fs.mkdirSync(path.join(projectPath, '.tenet', '.state'), { recursive: true });
      fs.writeFileSync(path.join(projectPath, '.tenet', '.state', 'tenet.db'), 'db');
      fs.writeFileSync(path.join(projectPath, '.tenet', '.state', 'tenet.db-wal'), 'wal');
      execSync('git add -f .tenet/.state/tenet.db .tenet/.state/tenet.db-wal', {
        cwd: projectPath,
        stdio: 'ignore',
      });

      const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});
      detectTrackedStateFiles(projectPath);

      const message = warnSpy.mock.calls.map((call) => String(call[0])).join('\n');
      expect(message).toContain('tenet.db-wal');
      warnSpy.mockRestore();
    });

    it('does not warn when .tenet/.state exists but is untracked', () => {
      const projectPath = createTempDir();
      execSync('git init', { cwd: projectPath, stdio: 'ignore' });
      fs.mkdirSync(path.join(projectPath, '.tenet', '.state'), { recursive: true });
      fs.writeFileSync(path.join(projectPath, '.tenet', '.state', 'tenet.db'), 'db');

      const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});
      detectTrackedStateFiles(projectPath);

      expect(warnSpy).not.toHaveBeenCalled();
      warnSpy.mockRestore();
    });

    it('is a silent no-op outside a git work tree', () => {
      const projectPath = createTempDir();
      const warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

      expect(() => detectTrackedStateFiles(projectPath)).not.toThrow();
      expect(warnSpy).not.toHaveBeenCalled();

      warnSpy.mockRestore();
    });
  });
});

describe('mergeClaudeLocalSettings', () => {
  it('creates .claude/settings.local.json with Tenet tool allowlist when missing', () => {
    const projectPath = createTempDir();

    const status = mergeClaudeLocalSettings(projectPath);

    expect(status).toBe('created');
    const settingsPath = path.join(projectPath, '.claude', 'settings.local.json');
    expect(fs.existsSync(settingsPath)).toBe(true);

    const content = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    const allow = content.permissions.allow as string[];
    for (const name of TENET_MCP_TOOL_NAMES) {
      expect(allow).toContain(`mcp__tenet__${name}`);
    }
    expect(content.enabledMcpjsonServers).toContain('tenet');
  });

  it('additively merges into existing settings.local.json without removing other entries', () => {
    const projectPath = createTempDir();
    const settingsPath = path.join(projectPath, '.claude', 'settings.local.json');
    fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
    fs.writeFileSync(
      settingsPath,
      JSON.stringify({
        permissions: { allow: ['Bash(git status)', 'mcp__other__existing_tool'] },
        enabledMcpjsonServers: ['other-server'],
        customKey: 'preserve-me',
      }),
      'utf8',
    );

    const status = mergeClaudeLocalSettings(projectPath);
    expect(status).toBe('merged');

    const content = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    expect(content.permissions.allow).toContain('Bash(git status)');
    expect(content.permissions.allow).toContain('mcp__other__existing_tool');
    expect(content.permissions.allow).toContain('mcp__tenet__tenet_init');
    expect(content.enabledMcpjsonServers).toContain('other-server');
    expect(content.enabledMcpjsonServers).toContain('tenet');
    expect(content.customKey).toBe('preserve-me');
  });

  it('returns "unchanged" when Tenet tools are already allowed', () => {
    const projectPath = createTempDir();
    mergeClaudeLocalSettings(projectPath);
    const status = mergeClaudeLocalSettings(projectPath);
    expect(status).toBe('unchanged');
  });

  it('adds Playwright allowlist without removing Tenet entries', () => {
    const projectPath = createTempDir();
    mergeClaudeLocalSettings(projectPath);

    const status = mergeClaudePlaywrightSettings(projectPath);
    expect(status).toBe('merged');

    const settingsPath = path.join(projectPath, '.claude', 'settings.local.json');
    const content = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    expect(content.enabledMcpjsonServers).toContain('tenet');
    expect(content.enabledMcpjsonServers).toContain('playwright');
    expect(content.permissions.allow).toContain('mcp__tenet__tenet_init');
    expect(content.permissions.allow).toContain('mcp__playwright__browser_navigate');
  });

  it('skips with invalid JSON status when settings.local.json is malformed', () => {
    const projectPath = createTempDir();
    const settingsPath = path.join(projectPath, '.claude', 'settings.local.json');
    fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
    fs.writeFileSync(settingsPath, '{ not json', 'utf8');

    const status = mergeClaudeLocalSettings(projectPath);
    expect(status).toBe('skipped_invalid_json');
    // File is left untouched
    expect(fs.readFileSync(settingsPath, 'utf8')).toBe('{ not json');
  });
});

describe('mergeOpenCodePermission', () => {
  it('adds permission.mcp.tenet="allow" to existing opencode.json without overwriting existing config', () => {
    const projectPath = createTempDir();
    const configPath = path.join(projectPath, 'opencode.json');
    fs.writeFileSync(
      configPath,
      JSON.stringify({
        model: 'claude-sonnet',
        mcp: { tenet: { type: 'local', command: ['tenet', 'serve'] } },
        permission: { bash: 'ask' },
      }),
      'utf8',
    );

    const status = mergeOpenCodePermission(projectPath);
    expect(status).toBe('merged');

    const content = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    expect(content.model).toBe('claude-sonnet');
    expect(content.mcp.tenet).toBeDefined();
    expect(content.permission.bash).toBe('ask');
    expect(content.permission.mcp.tenet).toBe('allow');
  });

  it('returns "unchanged" when tenet already has allow permission', () => {
    const projectPath = createTempDir();
    const configPath = path.join(projectPath, 'opencode.json');
    fs.writeFileSync(
      configPath,
      JSON.stringify({ permission: { mcp: { tenet: 'allow' } } }),
      'utf8',
    );

    const status = mergeOpenCodePermission(projectPath);
    expect(status).toBe('unchanged');
  });

  it('skips on invalid JSON', () => {
    const projectPath = createTempDir();
    const configPath = path.join(projectPath, 'opencode.json');
    fs.writeFileSync(configPath, 'not json', 'utf8');

    const status = mergeOpenCodePermission(projectPath);
    expect(status).toBe('skipped_invalid_json');
  });

  it('adds permission.mcp.playwright="allow" without overwriting Tenet', () => {
    const projectPath = createTempDir();
    const configPath = path.join(projectPath, 'opencode.json');
    fs.writeFileSync(
      configPath,
      JSON.stringify({ permission: { mcp: { tenet: 'allow' } } }),
      'utf8',
    );

    const status = mergeOpenCodePlaywrightPermission(projectPath);
    expect(status).toBe('merged');

    const content = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    expect(content.permission.mcp.tenet).toBe('allow');
    expect(content.permission.mcp.playwright).toBe('allow');
  });
});

describe('mergeCodexProjectTrust', () => {
  it('appends [projects."<abs>"] trust_level="trusted" when missing', () => {
    const projectPath = createTempDir();
    const configPath = path.join(projectPath, '.codex', 'config.toml');
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    fs.writeFileSync(configPath, '[mcp_servers.tenet]\ncommand = "tenet"\nargs = ["serve"]\n', 'utf8');

    const status = mergeCodexProjectTrust(projectPath);
    expect(status).toBe('merged');

    const content = fs.readFileSync(configPath, 'utf8');
    expect(content).toContain('[mcp_servers.tenet]');
    const absPath = fs.realpathSync(path.resolve(projectPath));
    expect(content).toContain(`[projects."${absPath}"]`);
    expect(content).toContain('trust_level = "trusted"');
  });

  it('creates the config when it does not exist', () => {
    const projectPath = createTempDir();
    const status = mergeCodexProjectTrust(projectPath);
    expect(status).toBe('created');

    const configPath = path.join(projectPath, '.codex', 'config.toml');
    expect(fs.existsSync(configPath)).toBe(true);
    const content = fs.readFileSync(configPath, 'utf8');
    expect(content).toContain('trust_level = "trusted"');
  });

  it('returns "unchanged" when already trusted', () => {
    const projectPath = createTempDir();
    mergeCodexProjectTrust(projectPath);
    const status = mergeCodexProjectTrust(projectPath);
    expect(status).toBe('unchanged');
  });

  it('respects existing trust_level="untrusted" and does NOT overwrite', () => {
    const projectPath = createTempDir();
    const configPath = path.join(projectPath, '.codex', 'config.toml');
    fs.mkdirSync(path.dirname(configPath), { recursive: true });
    const absPath = fs.realpathSync(path.resolve(projectPath));
    fs.writeFileSync(
      configPath,
      `[projects."${absPath}"]\ntrust_level = "untrusted"\n`,
      'utf8',
    );

    const status = mergeCodexProjectTrust(projectPath);
    expect(status).toBe('skipped_user_untrusted');

    // File is not changed
    const content = fs.readFileSync(configPath, 'utf8');
    expect(content).toContain('trust_level = "untrusted"');
    expect(content).not.toContain('trust_level = "trusted"');
  });
});
